name: get-content
description: Get file contents
category: filesystem
shell: powershell
flags:
  - flag: "-Path"
    takes_value: true
  - flag: "-Tail"
    takes_value: true
  - flag: "-TotalCount"
    takes_value: true
  - flag: "-LiteralPath"
    takes_value: true
  - flag: "-Raw"
  - flag: "-Encoding"
    takes_value: true
  - flag: "-Stream"
    takes_value: true
  - flag: "-Delimiter"
    takes_value: true
  - flag: "-Force"
allows_path_args: true
stdin: false
stdout: true
