name: get-winevent
description: Get events from event logs
category: logs
shell: powershell
timeout: 60
flags:
  - flag: "-LogName"
    takes_value: true
  - flag: "-MaxEvents"
    takes_value: true
  - flag: "-FilterHashtable"
    takes_value: true
  - flag: "-FilterXPath"
    takes_value: true
  - flag: "-FilterXml"
    takes_value: true
  - flag: "-ProviderName"
    takes_value: true
  - flag: "-ComputerName"
    takes_value: true
  - flag: "-ListLog"
    takes_value: true
  - flag: "-ListProvider"
    takes_value: true
  - flag: "-Oldest"
  - flag: "-Path"
    takes_value: true
  - flag: "-Force"
stdin: false
stdout: true
