name: get-nettcpconnection
description: Get TCP connection information
category: network
shell: powershell
flags:
  - flag: "-State"
    takes_value: true
  - flag: "-LocalPort"
    takes_value: true
  - flag: "-LocalAddress"
    takes_value: true
  - flag: "-RemoteAddress"
    takes_value: true
  - flag: "-RemotePort"
    takes_value: true
  - flag: "-OwningProcess"
    takes_value: true
  - flag: "-AppliedSetting"
    takes_value: true
stdin: false
stdout: true
