name: measure-object
description: Calculate numeric properties of objects
category: utility
shell: powershell
flags:
  - flag: "-Sum"
  - flag: "-Average"
  - flag: "-Maximum"
  - flag: "-Minimum"
  - flag: "-Property"
    takes_value: true
  - flag: "-Line"
  - flag: "-Word"
  - flag: "-Character"
  - flag: "-StandardDeviation"
  - flag: "-AllStats"
  - flag: "-IgnoreWhiteSpace"
stdin: true
stdout: true
