name: ps
description: Report process status
category: process
flags:
  - flag: "-e"
  - flag: "-f"
  - flag: "-o"
    takes_value: true
  - flag: "--sort"
    takes_value: true
  - flag: "-p"
    takes_value: true
  - flag: "-u"
    takes_value: true
  - flag: "-C"
    takes_value: true
  - flag: "--no-headers"
stdin: false
stdout: true
