name: ss
description: Investigate sockets
category: network
shell: bash
flags:
  - flag: "-t"
  - flag: "-u"
  - flag: "-l"
  - flag: "-n"
  - flag: "-p"
  - flag: "-s"
    description: "Print summary statistics"
  - flag: "-a"
    description: "Show both listening and non-listening sockets"
  - flag: "-e"
    description: "Show detailed socket information"
  - flag: "-m"
    description: "Show socket memory usage"
  - flag: "-i"
    description: "Show internal TCP information"
  - flag: "-x"
    description: "Show Unix domain sockets"
  - flag: "-4"
  - flag: "-6"
stdin: false
stdout: true
